config/routes.rb
Rails.application.routes.draw do

  # CREATE : 1) get a new task 2) post a new task
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  # READ: 1) list all 2) get all details for one
  get "tasks", to: "tasks#index"

  get "tasks/:id", to: "tasks#show", as: :task # le as: :task permet de définir le préfixe des routes

  # UPDATE: 1) get the form 2) edit the form

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  # DELETE: 1) destroy by id

  delete "tasks/:id", to: "tasks#destroy", as: :destroy_task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
      @tasks = Task.all
    end

    def show
      @task = Task.find(params[:id])
    end

    def new
      @task = Task.new # Needed to instantiate the form_for
    end

    def create
      @task = Task.new(task_params)
      @task.save # Will raise ActiveModel::ForbiddenAttributesError

      redirect_to task_path(@task)
    end

    def edit
      @task = Task.find(params[:id])
    end

    def update
      @task = Task.find(params[:id])
      @task.update(task_params)
      # No need for app/views/restaurants/update.html.erb
      redirect_to task_path(@task)
    end

    def destroy
      @task = Task.find(params[:id])
      @task.destroy
      # No need for app/views/restaurants/destroy.html.erb
      redirect_to tasks_path, status: :see_other
    end

    private

    def task_params
      params.require(:task).permit(:title, :details, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.number_field :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<h2>My tasks:</h2>
<% @tasks.each do |task|%>
<p><%= link_to task.title, task_path(task)  %></p>
<% end %>


<p><%= link_to 'Create a New Task!', tasks_new_path %></p>

app/views/tasks/new.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<p><%= link_to 'Homepage', tasks_path  %></p>
<p><%= link_to 'Edit', edit_task_path  %></p>
<%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>